# Site settings

title: UCC STEM
email: your-email@domain.com
description: 
  UCC Blog and Site of STEM related
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://yourdomain.com' # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
include: ['_pages']

defaults:
- scope:
    path: ""
    type: "events"
  values:
    layout: "post"
- scope:
    path: ""
    type: "articles"
  values:
    layout: "article"
- scope:
    path: ""
    type: "clubs"
  values:
    layout: "post"
    
# collections
collections:
  events:
    output: true
    permalink: /events/:name
  articles:
    output: true
    permalink: /articles/:name
  clubs:
    output: true
    permalink: /clubs/:name